FROM wmbbn/hume:R2022_03_21

ADD ./conf/hume-oiad-config.json /extra/config.json

ENTRYPOINT ["/usr/local/envs/hat_new/bin/python3"]
CMD ["/wm_rootfs/git/Hume/src/python/concept_discovery_dart_integration/concept_discovery_online/api.py", "--config", "/extra/config.json" ]